name: hello-world
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: First job
        run: echo "This runs first"
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Second job
        run: echo "This runs after the first job"
